Cosine similarity is a measure used to determine how similar two vectors are, particularly in the context of text data or other high-dimensional data representations.

cosine_similarity computes the cosine similarity between the TF-IDF vectors of the text documents.

importing dependencies

In [ ]:
import numpy as np
import pandas as pd
import difflib # A module providing classes and functions for comparing sequences.
# convert text documents into numerical vectors based on the frequency of words while considering the importance of each word in the entire data.
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data collection and preprocessing

In [ ]:
# loading the data from the esv file to apandas dataframe
movies= pd.read_csv('/content/movies (1).csv')

In [ ]:
movies.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [ ]:
movies.shape

(4803, 24)

In [ ]:
movies.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
selected_features = ['genres', 'keywords', 'tagline', 'cast', 'director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']

In [ ]:
# replacing the null valuess with null string
for feature in selected_features:
   movies[feature]=movies[feature].fillna('')

In [ ]:
# combining all the 5 selected features
combined_features = movies[ 'genres']+' '+movies[ 'keywords']+' '+movies[ 'tagline']+' '+movies[ 'cast']+movies['director']

In [ ]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [ ]:
# converting the text data to feature vectors
vectorizer =TfidfVectorizer()

In [ ]:
# Import the TfidfVectorizer class from the correct module
from sklearn.feature_extraction.text import TfidfVectorizer

# converting the text data to feature vectors
vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 208)	0.07667385108184376
  (0, 289)	0.08800104830707552
  (0, 6241)	0.1083630860656862
  (0, 16345)	0.10110130418423781
  (0, 6437)	0.10110130418423781
  (0, 4357)	0.2086788913449303
  (0, 3615)	0.21664083919579374
  (0, 6923)	0.1606391519765174
  (0, 17262)	0.33130376319063676
  (0, 19787)	0.12241864673585882
  (0, 3806)	0.24348426965339803
  (0, 17147)	0.2086788913449303
  (0, 5865)	0.23437015044361997
  (0, 18275)	0.06921925370543773
  (0, 20389)	0.12507033381973537
  (0, 13517)	0.08827534630310274
  (0, 13860)	0.26544401841252097
  (0, 16062)	0.15564527461690644
  (0, 20398)	0.23860058795491665
  (0, 20721)	0.19702892145320783
  (0, 16029)	0.21898867021233073
  (0, 16879)	0.20091311266965015
  (0, 19900)	0.19827148152003798
  (0, 17532)	0.16181995525842374
  (0, 10559)	0.22730069036139045
  :	:
  (4801, 423)	0.19056341009568284
  (4801, 5734)	0.2563183496274323
  (4801, 20694)	0.29933113097807007
  (4801, 16621)	0.28905348514055085
  (4801, 20559)	0.3138166592040448
  (4801, 4145)	0.3138166592040448
  (4801, 15864)	0.3138166592040448
  (4801, 16765)	0.3138166592040448
  (4801, 8776)	0.3138166592040448
  (4802, 13485)	0.1812883618371389
  (4802, 5347)	0.17030049967383565
  (4802, 2454)	0.1755983510178846
  (4802, 5908)	0.1712024779337688
  (4802, 7301)	0.18320658286238686
  (4802, 4057)	0.22511280012954266
  (4802, 5357)	0.19894359173578305
  (4802, 1488)	0.20002303752562678
  (4802, 15620)	0.17612508460823412
  (4802, 5167)	0.15607460606564647
  (4802, 2856)	0.24353543417297582
  (4802, 7663)	0.23018746318092126
  (4802, 4323)	0.26635394130052475
  (4802, 6353)	0.23965799931641568
  (4802, 8414)	0.5783448968561475
  (4802, 5463)	0.28917244842807377

Cosine similarity

In [ ]:
similarity = cosine_similarity(feature_vectors)

print(similarity)

[[1.         0.07047992 0.01423497 ... 0.         0.         0.        ]
 [0.07047992 1.         0.03271772 ... 0.03557523 0.         0.        ]
 [0.01423497 0.03271772 1.         ... 0.         0.02997687 0.        ]
 ...
 [0.         0.03557523 0.         ... 1.         0.         0.02941525]
 [0.         0.         0.02997687 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.02941525 0.         1.        ]]

In [ ]:
print(similarity.shape)

(4803, 4803)

Getting the movie name from the user

In [ ]:
# getting the movie name from the user
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : avathar

In [ ]:
# creating a list with all the movie names given in the dataset
list_of_all_titles = movies['title'].tolist()
print (list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'Shin Godzilla', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', 'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Asterix at the Olympic Games', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', 'The Flowers of War', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'The Messenger: The Story of Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'Th

In [ ]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Avatar', 'Sahara']

In [ ]:
close_match = find_close_match[0]
print(close_match)

Avatar

In [ ]:
# finding the index of the movie with title
index_of_the_movie= movies[movies.title == close_match]['index']. values [0]
print(index_of_the_movie)

0

In [ ]:
# getting a list of similar movies
similarity_score = list (enumerate(similarity[index_of_the_movie]))
print (similarity_score)

[(0, 1.0), (1, 0.07047992048783441), (2, 0.014234966337985912), (3, 0.012042393585625782), (4, 0.10303584920621583), (5, 0.039646969992973874), (6, 0.008253299608334727), (7, 0.03542608985212621), (8, 0.02839226032099458), (9, 0.025759395260813427), (10, 0.07646868228779594), (11, 0.012464386913520486), (12, 0.026500807339655402), (13, 0.01738819334131477), (14, 0.0675232633723781), (15, 0.01908806563891089), (16, 0.03357441890273434), (17, 0.025019336469238256), (18, 0.055068305083916545), (19, 0.0379431448964936), (20, 0.037911084236649024), (21, 0.011683231106742454), (22, 0.02964791525852308), (23, 0.04647738376634353), (24, 0.04428539430540286), (25, 0.029770414586111862), (26, 0.06921267258903238), (27, 0.03603003941305631), (28, 0.039204339760515995), (29, 0.014334739794117984), (30, 0.04150611297650281), (31, 0.05881242826902948), (32, 0.02927159427411831), (33, 0.03503946664597732), (34, 0.0), (35, 0.036045585810476684), (36, 0.04746732509843672), (37, 0.04728806994869435), (38, 0.02606049092669259), (39, 0.037647783923120036), (40, 0.013436569157813865), (41, 0.0330086282824578), (42, 0.0), (43, 0.1377800846294839), (44, 0.032856817482462955), (45, 0.02441885688402349), (46, 0.07985057348933929), (47, 0.19415099297357996), (48, 0.026575597002899014), (49, 0.010965516631330947), (50, 0.05576522036992011), (51, 0.02893567235916266), (52, 0.035564029674686616), (53, 0.04988720417060497), (54, 0.007194577455115329), (55, 0.014822152207051131), (56, 0.14510719261301117), (57, 0.014334041899095708), (58, 0.012573961555566053), (59, 0.06011942449616682), (60, 0.0), (61, 0.10391656664114984), (62, 0.013654890553632525), (63, 0.03744427979170503), (64, 0.026158592242856573), (65, 0.0060513679384382015), (66, 0.012153236147590507), (67, 0.029777763421501794), (68, 0.03229579644860707), (69, 0.031179438133943742), (70, 0.03392209988977568), (71, 0.03345043354675771), (72, 0.045104328784653855), (73, 0.019798594047451594), (74, 0.042214815890883814), (75, 0.02297394411920554), (76, 0.034804008248995516), (77, 0.004733176910130427), (78, 0.021650944801752822), (79, 0.044471740979957486), (80, 0.0536127161713203), (81, 0.05191703759495518), (82, 0.0917793147629523), (83, 0.03650551961327342), (84, 0.021357676290601764), (85, 0.06720741599017928), (86, 0.04196809121468719), (87, 0.04375991756851684), (88, 0.026040073990139273), (89, 0.01799098170934888), (90, 0.019406597568364475), (91, 0.03374165147345962), (92, 0.028290440621693707), (93, 0.05027552168922715), (94, 0.22428336595441223), (95, 0.04512262720026832), (96, 0.06031170699982416), (97, 0.02783786457886247), (98, 0.03313748319614191), (99, 0.029915707289284808), (100, 0.011244742986116938), (101, 0.05901428191396142), (102, 0.05035615785104162), (103, 0.03135082465752161), (104, 0.022619288135799828), (105, 0.012025184288745216), (106, 0.059540322698674875), (107, 0.027215697639081538), (108, 0.11200086920343617), (109, 0.014375601165272495), (110, 0.040344133518935246), (111, 0.06866747625183003), (112, 0.04136390372572653), (113, 0.032619331245999424), (114, 0.025454006347586294), (115, 0.02498163710311012), (116, 0.05494332186843876), (117, 0.018036644229468837), (118, 0.011307522650404014), (119, 0.011304725310122454), (120, 0.004769642056139384), (121, 0.03305767787283733), (122, 0.042798088215042676), (123, 0.051951298802911924), (124, 0.018504079173033292), (125, 0.05209055479216744), (126, 0.028541332936288015), (127, 0.06483252868797547), (128, 0.0), (129, 0.02628664242806178), (130, 0.006994594314420936), (131, 0.0774628509662833), (132, 0.08779790376969807), (133, 0.04369046972125412), (134, 0.013032941263462971), (135, 0.008917679956589155), (136, 0.006968552569958832), (137, 0.01299195471764603), (138, 0.03896038553063001), (139, 0.01661157920952717), (140, 0.011221947987476538), (141, 0.06271077872799663), (142, 0.008458567603488835), (143, 0.020304918549720614), (144, 0.00790736946505842), (145, 0.03189431512670223), (146, 0.0), (147, 0.06255539065588736), (148, 0.017796631103613528), (149, 0.0575201741246116), (150, 0.10752887584660256), (151, 0.013369493651399136), (152, 0.017461192345002145), (153, 0.012972644861423526), (154, 0.011783824949593204), (155, 0.0), (156, 0.0684819079246489), (157, 0.014672409380151862), (158, 0.1263142692867137), (159, 0.024213600908351098), (160, 0.030894576551148245), (161, 0.015654968785032145), (162, 0.043220322195130625), (163, 0.031312461468239364), (164, 0.029782636076534266), (165, 0.06269911543432166), (166, 0.04024133164054913), (167, 0.02191242006911927), (168, 0.045209987686875105), (169, 0.06488445035836471), (170, 0.01956545918508784), (171, 0.02776029626466235), (172, 0.023729231002447268), (173, 0.0), (174, 0.03094780335751174), (175, 0.03868389344564879), (176, 0.011730061033352652), (177, 0.0), (178, 0.007342259948187334), (179, 0.013018480118964766), (180, 0.006368296426282098), (181, 0.008063063197357993), (182, 0.0333963898629843), (183, 0.036096184447858705), (184, 0.09678512553340021), (185, 0.028421803139523364), (186, 0.02298897010744805), (187, 0.03208359317245739), (188, 0.02215666396908129), (189, 0.05104978876253698), (190, 0.01470392484408227), (191, 0.024105464214349146), (192, 0.031180137169565695), (193, 0.03650738173295624), (194, 0.0), (195, 0.023613861748704258), (196, 0.05421772431611002), (197, 0.030031112855779425), (198, 0.022872711326795726), (199, 0.03492632214748323), (200, 0.05030077902980705), (201, 0.005234270889546616), (202, 0.00757077064758946), (203, 0.03610239508170475), (204, 0.010942103751486253), (205, 0.019295773588509944), (206, 0.14533374345002856), (207, 0.03206617914241437), (208, 0.02894129212996301), (209, 0.0061691060775207985), (210, 0.017213619501694404), (211, 0.016724413251341875), (212, 0.052669834144498884), (213, 0.02028927393112234), (214, 0.0050621258292799474), (215, 0.045737270373613775), (216, 0.017752471343736063), (217, 0.055437112457678586), (218, 0.006922067259707382), (219, 0.05377621522523886), (220, 0.029976341902005578), (221, 0.008418506472621112), (222, 0.08637093852870795), (223, 0.09127945385237668), (224, 0.08097185390665146), (225, 0.0395377937331875), (226, 0.0), (227, 0.035167993620632484), (228, 0.08516470825564358), (229, 0.04002857223004507), (230, 0.02713530288572661), (231, 0.0), (232, 0.07120318052718774), (233, 0.028660122557486397), (234, 0.04145994961921183), (235, 0.018463511691818462), (236, 0.05183308762526904), (237, 0.017603333971282276), (238, 0.042362043275149544), (239, 0.17255753982700223), (240, 0.01887565908596689), (241, 0.05152691121206632), (242, 0.03678813012043104), (243, 0.025586340929034553), (244, 0.005069522731992467), (245, 0.044443937657851026), (246, 0.02747830125625966), (247, 0.00450632109076309), (248, 0.006222879007689528), (249, 0.05481253148345839), (250, 0.013388128066271614), (251, 0.0), (252, 0.04170904980610343), (253, 0.0181376870478402), (254, 0.01867591819689734), (255, 0.0), (256, 0.08244201904051697), (257, 0.026522793728639665), (258, 0.011851431009102778), (259, 0.021348765234349455), (260, 0.034481325132374105), (261, 0.012229208991510945), (262, 0.025053779110795583), (263, 0.013412922380330431), (264, 0.0), (265, 0.01664100658724474), (266, 0.02701194714953244), (267, 0.049175277809116034), (268, 0.016895742265350074), (269, 0.0), (270, 0.031001648550685292), (271, 0.04571322415984867), (272, 0.0), (273, 0.005632196175146579), (274, 0.0147141917459127), (275, 0.054118582786156076), (276, 0.02472358581909497), (277, 0.013662939365127559), (278, 0.13045599493378154), (279, 0.05971727632068827), (280, 0.0), (281, 0.04808961754755625), (282, 0.03192618508153043), (283, 0.006607589511397703), (284, 0.0), (285, 0.014285905783744429), (286, 0.03305227273462979), (287, 0.05699528162269847), (288, 0.0), (289, 0.018919875813285712), (290, 0.029901420159606618), (291, 0.02436910909197139), (292, 0.04899969792486953), (293, 0.018234611177220996), (294, 0.05134664541608501), (295, 0.005839143883206889), (296, 0.02393692981651514), (297, 0.014295109510618841), (298, 0.0), (299, 0.01840895460002894), (300, 0.07795175967061944), (301, 0.049192505262146934), (302, 0.019896790944294078), (303, 0.0062569127085447184), (304, 0.01325195530692095), (305, 0.10925701034704921), (306, 0.029170888117611447), (307, 0.013321617176473979), (308, 0.009402371666373126), (309, 0.02198707226980454), (310, 0.018443804136106794), (311, 0.08899431232061512), (312, 0.032319574459048775), (313, 0.011482179559268453), (314, 0.010121932109327866), (315, 0.031373190426812095), (316, 0.050732751012840596), (317, 0.01473219454895526), (318, 0.02311848954610351), (319, 0.04176128424666152), (320, 0.0449730931126339), (321, 0.004639828332466904), (322, 0.10376190977775956), (323, 0.0), (324, 0.023381942939854468), (325, 0.011558566215134384), (326, 0.016954477389767464), (327, 0.02586495990686693), (328, 0.004022779099523659), (329, 0.04254265157260701), (330, 0.025901891188692426), (331, 0.034250301712786056), (332, 0.024740051691599933), (333, 0.018307612842467708), (334, 0.05993086326361573), (335, 0.026756003859543027), (336, 0.03252708830269728), (337, 0.0039350273125842005), (338, 0.015054139521623523), (339, 0.014638958289210252), (340, 0.03083465890624784), (341, 0.018783535839360713), (342, 0.10313136858149115), (343, 0.0049708012474253905), (344, 0.0049814056936768585), (345, 0.0066024599905038905), (346, 0.02656674771539828), (347, 0.012150401897619583), (348, 0.0077665396509501855), (349, 0.018716521989806265), (350, 0.059681842455679104), (351, 0.0), (352, 0.016401704646133497), (353, 0.008984517891600888), (354, 0.0), (355, 0.006165515450852974), (356, 0.014389952863667042), (357, 0.0), (358, 0.026499043764577762), (359, 0.007707015231739214), (360, 0.014831401888218878), (361, 0.026029324215861432), (362, 0.0541770124162536), (363, 0.04287118605149196), (364, 0.014689262150516918), (365, 0.07615154460075264), (366, 0.03265759467218528), (367, 0.012746399866920555), (368, 0.016970320212874895), (369, 0.08769698475718343), (370, 0.058523603402285476), (371, 0.03137945457275117), (372, 0.05460581645719327), (373, 0.08149347623405427), (374, 0.02828019530501037), (375, 0.0405465650822537), (376, 0.030417034338833134), (377, 0.020738897144810812), (378, 0.0), (379, 0.021955442988055504), (380, 0.018642284765948876), (381, 0.022716053018977146), (382, 0.012482311925301307), (383, 0.02498988698971341), (384, 0.039871514892988805), (385, 0.0), (386, 0.006133112530393511), (387, 0.03164646003684167), (388, 0.0), (389, 0.023549931301524083), (390, 0.012167578675936383), (391, 0.010886246274621795), (392, 0.0056260239541722264), (393, 0.04445806252825393), (394, 0.006044441303088186), (395, 0.025313974646930065), (396, 0.006262096706885074), (397, 0.0), (398, 0.012699453954747291), (399, 0.006858442854511373), (400, 0.0539113225734911), (401, 0.0472200668260298), (402, 0.01826646144816592), (403, 0.028484637511092547), (404, 0.03540573405668124), (405, 0.014733684651470683), (406, 0.0), (407, 0.010596014720569088), (408, 0.006059731959046556), (409, 0.0), (410, 0.04337114584217501), (411, 0.020649215241526846), (412, 0.04386651870205592), (413, 0.038549556221904036), (414, 0.03245102978551624), (415, 0.02899140437165236), (416, 0.011166614146949309), (417, 0.050783926593066527), (418, 0.0), (419, 0.05290387460176332), (420, 0.06680134033726776), (421, 0.0), (422, 0.04628563823296608), (423, 0.012404299180821308), (424, 0.014400839963352102), (425, 0.020207117616173085), (426, 0.04260371931478255), (427, 0.004911933774058691), (428, 0.061222532775819266), (429, 0.004232619864313678), (430, 0.0), (431, 0.01646807110830069), (432, 0.060758037222333194), (433, 0.011874947515797414), (434, 0.0), (435, 0.012019004907566194), (436, 0.0), (437, 0.029295025695975765), (438, 0.0), (439, 0.026926556376987657), (440, 0.0), (441, 0.027884246927113755), (442, 0.02304629236592782), (443, 0.010931156043819733), (444, 0.004287772402834314), (445, 0.0), (446, 0.010499489213193458), (447, 0.03317003927501796), (448, 0.03533638645600332), (449, 0.024776678498029107), (450, 0.020320175881304484), (451, 0.01173383736042697), (452, 0.010212257004442178), (453, 0.006250809268858775), (454, 0.026002360251225338), (455, 0.005818556503784), (456, 0.07547627482159525), (457, 0.0133815883290467), (458, 0.00773867798899559), (459, 0.00761864751928651), (460, 0.0), (461, 0.08838739104234408), (462, 0.014819037790368306), (463, 0.05447144482626988), (464, 0.0), (465, 0.0), (466, 0.07948807208390199), (467, 0.02873239089291898), (468, 0.029637926663131024), (469, 0.01686342370917006), (470, 0.02028961966855388), (471, 0.010078842790789105), (472, 0.024934510452275578), (473, 0.05206748847864447), (474, 0.0), (475, 0.015537695361070431), (476, 0.032165611714650065), (477, 0.0), (478, 0.013617752799682099), (479, 0.02197501166363944), (480, 0.04853930347757374), (481, 0.0), (482, 0.0), (483, 0.0759288289484773), (484, 0.01565331670962138), (485, 0.028830055451846876), (486, 0.024798615950510562), (487, 0.054797677776495204), (488, 0.024562917289437658), (489, 0.02518803313945139), (490, 0.03306893597824252), (491, 0.01180381065398187), (492, 0.0), (493, 0.008046958957861413), (494, 0.025150624276487156), (495, 0.04371121789769673), (496, 0.03373048736793271), (497, 0.005587273355941631), (498, 0.00712717581914152), (499, 0.0051456670040412), (500, 0.005638647761415234), (501, 0.03277790356143428), (502, 0.016052351967009125), (503, 0.032590332175932095), (504, 0.0), (505, 0.07707449712816182), (506, 0.0), (507, 0.03377174308535598), (508, 0.034035518909705784), (509, 0.0), (510, 0.09680790141378244), (511, 0.03570040291179726), (512, 0.07081742931950352), (513, 0.011229489958908507), (514, 0.009460487707768587), (515, 0.011235019966341171), (516, 0.042510530249388834), (517, 0.004689248335018573), (518, 0.04862745616993669), (519, 0.0), (520, 0.0), (521, 0.0), (522, 0.0), (523, 0.018905906878349758), (524, 0.0), (525, 0.023722047321908087), (526, 0.0), (527, 0.008060884487117266), (528, 0.033204889969462775), (529, 0.019239004960559466), (530, 0.006510535283874078), (531, 0.053339392324533164), (532, 0.0), (533, 0.044136254367029205), (534, 0.006688824408954973), (535, 0.02447021464019601), (536, 0.013916637243420677), (537, 0.02208567815119314), (538, 0.024861766431091788), (539, 0.11117536804597386), (540, 0.01735851327298075), (541, 0.07769267878661479), (542, 0.02867305506318035), (543, 0.03464147694333079), (544, 0.02573266164365679), (545, 0.018661128323197336), (546, 0.014752245099684745), (547, 0.031081992751237096), (548, 0.007541187800055515), (549, 0.08028360000168039), (550, 0.0), (551, 0.007576567463733964), (552, 0.0), (553, 0.006058946474244039), (554, 0.012435818323403482), (555, 0.016026288671302062), (556, 0.01857527942240289), (557, 0.03502416513477166), (558, 0.004272456821564233), (559, 0.0), (560, 0.017953099584535247), (561, 0.011007028133226598), (562, 0.04009269351193653), (563, 0.017321170193369456), (564, 0.019884473681549754), (565, 0.052170210236508016), (566, 0.011211685865912407), (567, 0.0), (568, 0.0357137360326568), (569, 0.023992044810336188), (570, 0.013557036953081605), (571, 0.01959839308362939), (572, 0.030242333494761416), (573, 0.006307367456326149), (574, 0.03689025935694934), (575, 0.05106221497775346), (576, 0.010161723583280156), (577, 0.10114475172048656), (578, 0.016539120355827733), (579, 0.04569522050089128), (580, 0.005647066656143619), (581, 0.0866554616827112), (582, 0.0595549311336797), (583, 0.026187550070302545), (584, 0.04995145478112543), (585, 0.05117722047293724), (586, 0.07724089144872068), (587, 0.06511513793145557), (588, 0.0), (589, 0.032381133058017694), (590, 0.005799347424018713), (591, 0.0516600315374772), (592, 0.036289237723236174), (593, 0.0), (594, 0.01365880634936914), (595, 0.05089904390969479), (596, 0.022489793918628747), (597, 0.043743689838463544), (598, 0.0), (599, 0.07472471729459115), (600, 0.022065268023598886), (601, 0.02836544506468703), (602, 0.024813913495360468), (603, 0.0040398030553654716), (604, 0.013358123368174445), (605, 0.0), (606, 0.0), (607, 0.05013002017730778), (608, 0.004529626251512445), (609, 0.028279560991822508), (610, 0.019688447099612694), (611, 0.018993883710584167), (612, 0.021101130470470505), (613, 0.005694149583681556), (614, 0.0), (615, 0.009725749323446756), (616, 0.0), (617, 0.03928598849183526), (618, 0.04486387570899548), (619, 0.0), (620, 0.009390598123896357), (621, 0.00540933676452001), (622, 0.006098037239554334), (623, 0.0), (624, 0.029709123624447376), (625, 0.004872379284870215), (626, 0.0575720637457111), (627, 0.06157034834098098), (628, 0.08784067160276332), (629, 0.004884336328676901), (630, 0.004208481900716565), (631, 0.014210600892831632), (632, 0.04645408969178265), (633, 0.014006642192863577), (634, 0.06591090254599209), (635, 0.0), (636, 0.011216709108842824), (637, 0.0), (638, 0.016998749126764474), (639, 0.0), (640, 0.013254775612035205), (641, 0.02462512923831347), (642, 0.08014613699035272), (643, 0.13234036702121044), (644, 0.03485337134387095), (645, 0.014111239783770692), (646, 0.010112652190585188), (647, 0.01854008629507112), (648, 0.013022573355599146), (649, 0.0), (650, 0.0), (651, 0.03158906074228578), (652, 0.004602190506332057), (653, 0.005944637960387865), (654, 0.03998186907557184), (655, 0.03326111380206276), (656, 0.009332456428579649), (657, 0.058040823906671646), (658, 0.03254196242646929), (659, 0.006127236703054999), (660, 0.017276375893576695), (661, 0.11660871656069696), (662, 0.0), (663, 0.005394576899794794), (664, 0.013547733578322957), (665, 0.011797565692318416), (666, 0.02008178768187511), (667, 0.0), (668, 0.01740582122705557), (669, 0.0), (670, 0.02368273492296259), (671, 0.034743696216087), (672, 0.01720931214003989), (673, 0.030847823124106562), (674, 0.03316344578654781), (675, 0.06181123872862071), (676, 0.025165248438036154), (677, 0.0599059884888884), (678, 0.027015155918963793), (679, 0.0), (680, 0.04519304295671368), (681, 0.026320035179577456), (682, 0.0), (683, 0.01258320699667855), (684, 0.0), (685, 0.005945367902400791), (686, 0.0), (687, 0.0276652009688), (688, 0.0), (689, 0.005523703814630399), (690, 0.012094312142092348), (691, 0.017148413462032126), (692, 0.06654246129042439), (693, 0.0), (694, 0.01483507337217058), (695, 0.011849227422473421), (696, 0.005293908859431623), (697, 0.004830827018391316), (698, 0.04018332752851042), (699, 0.0), (700, 0.005981894241403083), (701, 0.0), (702, 0.005918370252565154), (703, 0.0), (704, 0.007786795147787396), (705, 0.0), (706, 0.013414297398116422), (707, 0.007910305683289374), (708, 0.014299194302854142), (709, 0.0), (710, 0.013515011796800393), (711, 0.011640172298794948), (712, 0.0293310081415421), (713, 0.025497939808130532), (714, 0.0), (715, 0.029665051836039465), (716, 0.013435327017111663), (717, 0.004938443760582456), (718, 0.020978092060943254), (719, 0.0), (720, 0.04137098243071445), (721, 0.011505129808041963), (722, 0.014994290655584408), (723, 0.020951235255638644), (724, 0.005770675191582147), (725, 0.0), (726, 0.0049902279315670196), (727, 0.0), (728, 0.039580514154255064), (729, 0.0), (730, 0.010709534973442611), (731, 0.030095637890109557), (732, 0.07228659724045178), (733, 0.02340654227232167), (734, 0.007329015810209985), (735, 0.03348179877839627), (736, 0.017863729740414357), (737, 0.0062829625423969976), (738, 0.0), (739, 0.025153208963273124), (740, 0.11152524543054543), (741, 0.013148183880155095), (742, 0.010381050565389589), (743, 0.028886310157545978), (744, 0.03768742735182069), (745, 0.005498291583743739), (746, 0.022416714948630706), (747, 0.006091586027064346), (748, 0.008220121980059052), (749, 0.0), (750, 0.013523987885385742), (751, 0.0), (752, 0.034009141166218525), (753, 0.010919157766284628), (754, 0.024088344072045704), (755, 0.03470904550474271), (756, 0.0), (757, 0.0), (758, 0.013574055129759649), (759, 0.012254728547567567), (760, 0.0), (761, 0.014262549092503372), (762, 0.0144901548032182

In [ ]:
len(similarity_score)

4803

In [ ]:
# sorting the movies based on their similarity score

sorted_similar_movies= sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(0, 1.0), (3158, 0.24281054779819294), (94, 0.22428336595441223), (2403, 0.21834288638853935), (1053, 0.1944312005064881), (47, 0.19415099297357996), (3730, 0.17462658937994255), (239, 0.17255753982700223), (838, 0.17126056784919289), (1531, 0.16405955117266408), (4593, 0.15787269145881902), (812, 0.15495135722488507), (4401, 0.15089803533018598), (1951, 0.149552784324097), (2696, 0.14674906811231614), (206, 0.14533374345002856), (770, 0.1452219679269991), (56, 0.14510719261301117), (43, 0.1377800846294839), (1759, 0.13649848859868877), (1473, 0.13322175379558765), (643, 0.13234036702121044), (278, 0.13045599493378154), (3208, 0.12753810810082164), (1650, 0.12682678856404786), (158, 0.1263142692867137), (1275, 0.12109234452819913), (1099, 0.12058462756986323), (3202, 0.11734833737420877), (855, 0.11683685733584315), (661, 0.11660871656069696), (4332, 0.11566475561852416), (3105, 0.11521915053341131), (942, 0.11463016084577676), (2060, 0.11280261648596361), (108, 0.11200086920343617), (2198, 0.1115343033829158), (740, 0.11152524543054543), (539, 0.11117536804597386), (4108, 0.11070921476201641), (1354, 0.11070046669298601), (1804, 0.11035197854496484), (305, 0.10925701034704921), (977, 0.10898689627473375), (3439, 0.10857376248551452), (150, 0.10752887584660256), (1990, 0.10595602878392636), (4387, 0.10582954877758756), (1259, 0.10556998925422713), (775, 0.10432748680492493), (61, 0.10391656664114984), (322, 0.10376190977775956), (1490, 0.1034171829782633), (342, 0.10313136858149115), (4, 0.10303584920621583), (3056, 0.10291838581206614), (2827, 0.10131571183412376), (577, 0.10114475172048656), (3184, 0.10028360003066926), (1914, 0.09952559210180292), (1178, 0.09862648076911948), (1245, 0.09742368116369717), (510, 0.09680790141378244), (184, 0.09678512553340021), (1922, 0.09258456806368562), (1976, 0.09193153265891803), (1448, 0.0918577576889329), (82, 0.0917793147629523), (2500, 0.09160504081067056), (2888, 0.0913292178931997), (223, 0.09127945385237668), (2278, 0.09103542406747474), (4114, 0.09023282804705066), (4783, 0.08961446775141231), (1083, 0.08942965270694977), (311, 0.08899431232061512), (1892, 0.08866307447533714), (3534, 0.08839956384910991), (461, 0.08838739104234408), (628, 0.08784067160276332), (2995, 0.087832557437544), (132, 0.08779790376969807), (369, 0.08769698475718343), (2778, 0.08751268565071701), (2350, 0.08687451320335315), (3538, 0.08679029220750496), (581, 0.0866554616827112), (222, 0.08637093852870795), (3593, 0.08586346510238535), (2129, 0.085605651377504), (4276, 0.08536003513094237), (2361, 0.08527837438434183), (228, 0.08516470825564358), (4507, 0.0851603326973576), (2244, 0.08502206565908602), (3203, 0.08490046067016802), (1379, 0.08427880344848088), (4637, 0.08418201404267783), (2391, 0.08315993396298804), (1309, 0.0831452783960176), (256, 0.08244201904051697), (4688, 0.0816901617569778), (1146, 0.08162183270503372), (373, 0.08149347623405427), (2829, 0.0812882610118785), (224, 0.08097185390665146), (549, 0.08028360000168039), (642, 0.08014613699035272), (46, 0.07985057348933929), (466, 0.07948807208390199), (3520, 0.07948706728515109), (2444, 0.07897089474547686), (2153, 0.07843233039557293), (4670, 0.0784249865007752), (2103, 0.07824240670073518), (300, 0.07795175967061944), (870, 0.07794269031988375), (3474, 0.07778117759433861), (2015, 0.07773697071865886), (541, 0.07769267878661479), (3405, 0.07750743622734758), (131, 0.0774628509662833), (1564, 0.07730228962468844), (1318, 0.07725114631248507), (586, 0.07724089144872068), (1633, 0.0772004755055477), (1217, 0.07709100801348359), (505, 0.07707449712816182), (1574, 0.07692431107114553), (2229, 0.07687727986438314), (1372, 0.07652709889348253), (10, 0.07646868228779594), (1296, 0.07645569791147452), (2781, 0.07638373589559469), (4301, 0.07635472743233986), (365, 0.07615154460075264), (483, 0.0759288289484773), (1787, 0.07592151162751329), (1959, 0.07591132108143027), (2638, 0.07581880594079816), (456, 0.07547627482159525), (2106, 0.07532667565138562), (1568, 0.07504854631837615), (3484, 0.07494847787222866), (599, 0.07472471729459115), (2262, 0.07450772745982395), (3624, 0.07434112077838173), (4394, 0.07354479170739651), (787, 0.07286895242006092), (1762, 0.072778838311604), (4073, 0.07266139196263052), (4450, 0.07260652264227666), (732, 0.07228659724045178), (2091, 0.07195785280635754), (232, 0.07120318052718774), (512, 0.07081742931950352), (1, 0.07047992048783441), (2934, 0.07005742811013849), (2114, 0.06966948050067005), (26, 0.06921267258903238), (994, 0.06887337416590279), (111, 0.06866747625183003), (1999, 0.06853717172506091), (156, 0.0684819079246489), (2427, 0.06844965525870787), (1468, 0.06826916116366687), (2584, 0.06797056222977599), (14, 0.0675232633723781), (3815, 0.06722593043376435), (85, 0.06720741599017928), (1932, 0.06705617447062649), (4109, 0.0668454066761595), (420, 0.06680134033726776), (2757, 0.06666229537889973), (2720, 0.06660890253595798), (692, 0.06654246129042439), (1577, 0.0664499375554812), (1459, 0.06642981223478729), (853, 0.06615139631963028), (634, 0.06591090254599209), (1938, 0.06561357967609815), (4193, 0.06559591233505041), (587, 0.06511513793145557), (1279, 0.06501825798322602), (169, 0.06488445035836471), (127, 0.06483252868797547), (1282, 0.06432337643718399), (2921, 0.06429553905664828), (1390, 0.06401674944237391), (813, 0.06387514415244826), (3445, 0.06347923711778868), (2986, 0.0633711855010789), (1506, 0.06336220199520803), (4381, 0.06332459367946718), (2138, 0.06307236564994993), (1213, 0.06300508776581092), (141, 0.06271077872799663), (165, 0.06269911543432166), (147, 0.06255539065588736), (3988, 0.062421993326193685), (2688, 0.06241001418257936), (932, 0.062037379414171125), (2127, 0.06195732763215003), (2442, 0.061935177138364814), (675, 0.06181123872862071), (2578, 0.06168483905031756), (922, 0.06165639135100172), (627, 0.06157034834098098), (3715, 0.06133527309722021), (428, 0.061222532775819266), (432, 0.060758037222333194), (2157, 0.06045165152369901), (1272, 0.060329083453700715), (96, 0.06031170699982416), (4465, 0.060279799106217474), (59, 0.06011942449616682), (1187, 0.059989978328310954), (334, 0.05993086326361573), (677, 0.0599059884888884), (1775, 0.059866409460567066), (279, 0.05971727632068827), (350, 0.059681842455679104), (582, 0.0595549311336797), (106, 0.059540322698674875), (889, 0.05944103921919506), (2592, 0.05930356872799421), (2914, 0.05919341346427995), (101, 0.05901428191396142), (3668, 0.05894231632714339), (2691, 0.05885874847581207), (31, 0.05881242826902948), (4149, 0.05874969822454135), (370, 0.058523603402285476), (2550, 0.058430487170646535), (3702, 0.05835461268977711), (3903, 0.05812936643551497), (657, 0.058040823906671646), (2163, 0.058011808333817666), (800, 0.05764196182317172), (626, 0.0575720637457111), (4039, 0.05752628113028663), (149, 0.0575201741246116), (1818, 0.05750843399247535), (2748, 0.0573477067903472), (2258, 0.05733328704911074), (2815, 0.05728071319272005), (287, 0.05699528162269847), (1358, 0.05676700083457797), (1086, 0.05637998382148742), (1535, 0.05621308636000287), (1902, 0.0561687156119744), (2522, 0.05585077637152887), (50, 0.05576522036992011), (1271, 0.05574712470553479), (2851, 0.0557405074438728), (1467, 0.055710626431843185), (4511, 0.055620305604566295), (1667, 0.05553700413621315), (1546, 0.055478504593746356), (217, 0.055437112457678586), (899, 0.05540710060904801), (1399, 0.0552913643442349), (1068, 0.055081550589676974), (18, 0.055068305083916545), (1411, 0.05504998892244031), (1850, 0.054985480952645424), (116, 0.05494332186843876), (249, 0.05481253148345839), (487, 0.054797677776495204), (3236, 0.05463868433143354), (372, 0.05460581645719327), (463, 0.05447144482626988), (1796, 0.054307736240104244), (196, 0.05421772431611002), (362, 0.0541770124162536), (3372, 0.05414720852633248), (275, 0.054118582786156076), (1654, 0.05407025281517223), (2433, 0.05399789658010248), (1873, 0.05399652313432149), (2965, 0.05391486410782065), (400, 0.0539113225734911), (219, 0.05377621522523886), (1191, 0.053728279046859076), (2247, 0.05372816286813868), (3177, 0.0537221435931384), (80, 0.0536127161713203), (531, 0.053339392324533164), (1265, 0.05325820776182256), (4448, 0.05309872938186232), (1230, 0.05309555340507058), (419, 0.05290387460176332), (2233, 0.05287710144352755), (1878, 0.05277541816794661), (4062, 0.05276936304930271), (212, 0.052669834144498884), (778, 0.05260173250681948), (2254, 0.05260066668233814), (2237, 0.052593302251075454), (2763, 0.05253743616244917), (1277, 0.052251659775168255), (1652, 0.05222462015362393), (565, 0.052170210236508016), (125, 0.05209055479216744), (4392, 0.05208300408019263), (3214, 0.052080774402841895), (473, 0.05206748847864447), (123, 0.051951298802911924), (1202, 0.05194929854983334), (81, 0.05191703759495518), (2898, 0.05191426236979276), (3014, 0.051872275650783874), (236, 0.05183308762526904), (591, 0.0516600315374772), (2155, 0.05164904762259758), (4741, 0.05159236493811658), (1395, 0.05154056327158892), (241, 0.05152691121206632), (3914, 0.05152578294420372), (3516, 0.051465268287529405), (4016, 0.05144352546578163), (1510, 0.05144042315948365), (4539, 0.0513925580485456), (294, 0.05134664541608501), (585, 0.05117722047293724), (2341, 0.05117705615658458), (3055, 0.051108158162630805), (2614, 0.05110490244549089), (575, 0.05106221497775346), (189, 0.05104978876253698), (2076, 0.05092754631417608), (1094, 0.05090687069756204), (595, 0.05089904390969479), (2991, 0.05083743064383295), (4327, 0.05081897119671523), (4651, 0.050797469741982154), (417, 0.050783926593066527), (773, 0.050754264032766755), (316, 0.050732751012840596), (3607, 0.05070765880334331), (4182, 0.05070415389400136), (102, 0.05035615785104162), (900, 0.050328179149027846), (200, 0.05030077902980705), (93, 0.05027552168922715), (3311, 0.05020526896016979), (2264, 0.05018368541602605), (607, 0.05013002017730778), (1625, 0.050012567828948695), (1617, 0.04999075383526387), (1877, 0.04995567117427484), (584, 0.04995145478112543), (836, 0.04992041470471454), (53, 0.04988720417060497), (1852, 0.04976147218169856), (1029, 0.04964743032513223), (1751, 0.049642946239443986), (2964, 0.04953923152929604), (3813, 0.049514239855203486), (3163, 0.04927610515888581), (2052, 0.049249076619076994), (301, 0.049192505262146934), (267, 0.049175277809116034), (1415, 0.04915160483706936), (1675, 0.04914242725734966), (1322, 0.04908784048809736), (2071, 0.04902773543934294), (292, 0.04899969792486953), (2024, 0.048941227609695714), (2639, 0.04892195127262407), (1939, 0.04882353670021251), (1015, 0.048800191321268796), (1794, 0.048655704082661885), (518, 0.04862745616993669), (480, 0.04853930347757374), (3899, 0.048523907274465664), (3012, 0.04841332896264024), (3374, 0.04840631904782782), (1611, 0.04827928426138354), (793, 0.048211394329350114), (281, 0.04808961754755625), (3323, 0.047688499876065174), (1007, 0.047505937076458234), (36, 0.04746732509843672), (3494, 0.04745752204988842), (854, 0.04745141152024936), (1239, 0.04731492484178443), (931, 0.04729216775235748), (1002, 0.0472906599818486), (37, 0.04728806994869435), (1106, 0.047277088737131594), (2053, 0.047271814469717274), (3505, 0.04723693694915334), (401, 0.0472200668260298), (2506, 0.04703715093022878), (4588, 0.04701008938966868), (2826, 0.04696521278356583), (1984, 0.04690595901331271), (4661, 0.046817161422917586), (3204, 0.04673215285695197), (3775, 0.04669211890380094), (1373, 0.046670619745791744), (1525, 0.04666211548173997), (2387, 0.046560007515734685), (23, 0.04647738376634353), (632, 0.04645408969178265), (2085, 0.04641931576381594), (422, 0.04628563823296608), (4321, 0.046108061589438566), (2253, 0.04603612561380855), (3350, 0.04590248235530507), (215, 0.045737270373613775), (271, 0.04571322415984867), (579, 0.04569522050089128), (1207, 0.04549815493483418), (764, 0.045334774419633364), (929, 0.045330064534201894), (1583, 0.045313922471881936), (4768, 0.04529036033860001), (4160, 0.0452896785270049), (3285, 0.04522831761669741), (168, 0.045209987686875105), (680, 0.04519304295671368), (3642, 0.04516416141128411), (2476, 0.0451474681395717), (95, 0.04512262720026832), (72, 0.045104328784653855), (1238, 0.045046196320714285), (320, 0.0449730931126339), (4786, 0.044924893029722156), (3294, 0.04488355253680936), (618, 0.04486387570899548), (2868, 0.044819654820343516), (1569, 0.04481123594161626), (1079, 0.044766171677860525), (2343, 0.044765121260581596), (2865, 0.04471692921670226), (1031, 0.04454003435024177), (79, 0.044471740979957486), (393, 0.04445806252825393), (245, 0.044443937657851026), (4225, 0.044415465972351284), (24, 0.04428539430540286), (1044, 0.044180611548611484), (3205, 0.044178426580969356), (2346, 0.044175532923703076), (533, 0.044136254367029205), (2313, 0.04399520207914986), (3197, 0.04395629776596884), (2514, 0.04395415054496218), (412, 0.04386651870205592), (2957, 0.043814802237509845), (1158, 0.04377288761530587), (1084, 0.04376308797267607), (87, 0.04375991756851684), (597, 0.043743689838463544), (495, 0.04371121789769673), (2717, 0.04369417678532094), (133, 0.04369046972125412), (3873, 0.043683217750136484), (1839, 0.04362997353821425), (3638, 0.043544484579518206), (2947, 0.04353364406235288), (1890, 0.04350057278499331), (3436, 0.04349018130026443), (410, 0.04337114584217501), (4245, 0.043343472664339244), (162, 0.043220322195130625), (2101, 0.043190043293899985), (1995, 0.04312709638652725), (2659, 0.04304998892249889), (972, 0.043043128118969355), (1291, 0.04298103452520402), (363, 0.04287118605149196), (769, 0.042831261805055844), (122, 0.042798088215042676), (426, 0.04260371931478255), (329, 0.04254265157260701), (516, 0.042510530249388834), (4376, 0.0424334739891239), (238, 0.042362043275149544), (1921, 0.042237882642780014), (74, 0.042214815890883814), (3068, 0.042088281701592546), (2352, 0.04207071027447283), (979, 0.042033833579471505), (4176, 0.042033410009606885), (86, 0.04196809121468719), (3885, 0.04192920895496213), (2753, 0.04188874071760282), (2966, 0.041874732020484466), (319, 0.04176128424666152), (252, 0.04170904980610343), (1192, 0.04170834810404188), (30, 0.04150611297650281), (234, 0.04145994961921183), (720, 0.04137098243071445), (112, 0.04136390372572653), (3613, 0.04120164552638963), (2546, 0.04113283540281287), (1016, 0.04103872368304156), (1944, 0.04102824760157922), (2047, 0.04096136642544228), (810, 0.040959818590440414), (1085, 0.04095774952298098), (2072, 0.040946580328917556), (1958, 0.0408569875897265), (1821, 0.04070262661720306), (4399, 0.04062739141784059), (2654, 0.04057124869395094), (375, 0.0405465650822537), (2650, 0.04050035094400793), (110, 0.040344133518935246), (878, 0.0403426247168346), (166, 0.04024133164054913), (698, 0.04018332752851042), (562, 0.04009269351193653), (229, 0.04002857223004507), (654, 0.03998186907557184), (384, 0.039871514892988805), (4788, 0.03984179747378468), (1808, 0.039660344328294656), (5, 0.039646969992973874), (728, 0.039580514154255064), (3568, 0.03957081620658793), (225, 0.0395377937331875), (1290, 0.039493720495062945), (2394, 0.039491647408983574), (1736, 0.03944713549021139), (1367, 0.03936804214902577), (4375, 0.03931640165555501), (617, 0.03928598849183526), (2835, 0.039244704952311284), (1500, 0.03921720940417309), (28, 0.039204339760515995), (1006, 0.03916356671852206), (1028, 0.03915710343151573), (3514, 0.039135170368218127), (1380, 0.03910375848670759), (4678, 0.03909527144444297), (2046, 0.03909020913191276), (1115, 0.03906949699476438), (4071, 0.039025387727219196), (1580, 0.03901247465820431), (2317, 0.039005741695436344), (1764, 0.03899463648219234), (3579, 0.038988228284813436), (2175, 0.03898519889521498), (3993, 0.03898052681334122), (138, 0.03896038553063001), (3227, 0.03890446543288431), (3692, 0.038866480644633196), (3006, 0.03879414555242128), (4608, 0.03877618156070316), (1428, 0.0387624868501666), (175, 0.03868389344564879), (2320, 0.03860618188267731), (413, 0.038549556221904036), (1134, 0.03853006419524713), (1913, 0.038488570016078215), (2018, 0.03846765130694156), (2016, 0.03845159132884439), (1294, 0.0384469498184677), (2515, 0.03841664377246709), (2239, 0.03835916132601069), (4703, 0.0383076804174116), (3901, 0.038295358297906035), (3929, 0.03819416213466327), (1008, 0.03809907591730238), (1159, 0.03809163706325331), (3837, 0.03805825338892352), (1672, 0.0380254500321606), (2798, 0.03799467764500935), (768, 0.03798748155159273), (19, 0.0379431448964936), (20, 0.037911084236649024), (3552, 0.03789468401732579), (1715, 0.03785828564455624), (3150, 0.037707431893675925), (2547, 0.03770634246504757), (744, 0.03768742735182069), (2994, 0.037666409072252265), (3044, 0.03764964842015797), (39, 0.037647783923120036), (799, 0.037556421007296954), (1110, 0.037527014620993386), (63, 0.03744427979170503), (1836, 0.03743858963586563), (2169, 0.03742308348520418), (1382, 0.03734634555348237), (4596, 0.03732564476765418), (2443, 0.03720174552305962), (1438, 0.037189187511848576), (2577, 0.037154459668546455), (920, 0.03696190797694445), (574, 0.03689025935694934), (3864, 0.0368306115980242), (242, 0.03678813012043104), (2561, 0.036754019954096384), (1404, 0.03672450072619249), (930, 0.03671912798994166), (3616, 0.03657344704921897), (3429, 0.03652092841200046), (193, 0.03650738173295624), (83, 0.03650551961327342), (4117, 0.03649436234973849), (832, 0.03643554191535265), (1298, 0.036421036888246654), (4644, 0.036363728619219486), (2357, 0.03632272746562627), (592, 0.036289237723236174), (3229, 0.036286859885705854), (3427, 0.03620279438492912), (3195, 0.036153714620808505), (1483, 0.036117691800303914), (203, 0.03610239508170475), (183, 0.036096184447858705), (1074, 0.03608903612338153), (35, 0.036045585810476684), (27, 0.03603003941305631), (784, 0.03600590328345312), (4251, 0.0359922692047464), (976, 0.03599056350960237), (1686, 0.03598899428490847), (969, 0.03594005279471886), (1977, 0.03593046511355903), (1802, 0.0359285637178434), (2978, 0.035920613178878506), (3800, 0.03591996789718291), (1523, 0.03587863798285949), (1872, 0.03585548521082556), (2625, 0.035844984309587914), (568, 0.0357137360326568), (511, 0.03570040291179726), (971, 0.035642682729952975), (52, 0.035564029674686616), (2435, 0.035526149209254676), (7, 0.03542608985212621), (404, 0.03540573405668124), (448, 0.03533638645600332), (3720, 0.03528772601041601), (1869, 0.035278445453092624), (4231, 0.03521343584513947), (227, 0.035167993620632484), (1750, 0.035125559162259824), (4325, 0.03504895836779705), (33, 0.03503946664597732), (557, 0.03502416513477166), (1918, 0.035009844935613516), (3239, 0.03500186652123857), (858, 0.03498404242715654), (1651, 0.034930851133800324), (199, 0.03492632214748323), (2927, 0.034875465007870886), (644, 0.03485337134387095), (76, 0.034804008248995516), (2022, 0.034769469727383887), (671, 0.034743696216087), (2892, 0.034726307118007574), (2211, 0.03472395103064751), (1930, 0.03471181918445221), (755, 0.03470904550474271), (4592, 0.0347058035452995), (1896, 0.034698633112425936), (543, 0.03464147694333079), (2901, 0.0346033532939056), (3296, 0.03458282387448404), (3305, 0.03450374569983162), (4761, 0.03448702287613045), (260, 0.034481325132374105), (2011, 0.034476666979802235), (2894, 0.03445947694937869), (2817, 0.03444249648734367), (2184, 0.0343537866086344), (1453, 0.03426801473467322), (331, 0.034250301712786056), (3764, 0.03423024881389014), (2967, 0.034221666046167346), (4613, 0.03421018937366003), (2066, 0.03420074017006494), (3734, 0.03414587061181825), (2806, 0.03406806648717174), (3011, 0.03404960119801921), (508, 0.034035518909705784), (752, 0.034009141166218525), (1410, 0.03400693775427354), (3979, 0.033963804330729756), (1636, 0.03395504284956211), (1405, 0.033944686052081494), (2006, 0.033929999744955655), (70, 0.03392209988977568), (1602, 0.03390009712768132), (2479, 0.033845700953308584), (507, 0.03377174308535598), (91, 0.03374165147345962), (496, 0.03373048736793271), (3406, 0.03372096368363203), (2336, 0.033717094225143886), (782

In [ ]:
# print the name of similar movies based on the index
print('Movies suggested for you : \n') #Removed extra space before print statement
i = 1
for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies[movies.iindex==index]['title']. values[0]
    if (i<30):
        print(i, '',title_from_index)
        i+=1

Movies suggested for you :

1  Avatar
2  Alien
3  Guardians of the Galaxy
4  Aliens
5  Galaxy Quest
6  Star Trek Into Darkness
7  Cargo
8  Gravity
9  Alien³
10  Moonraker
11  Trekkies
12  Pocahontas
13  The Helix... Loaded
14  Space Dogs
15  Jason X
16  Clash of the Titans
17  Event Horizon
18  Star Trek Beyond
19  Terminator Salvation
20  The Right Stuff
21  The Astronaut's Wife
22  Space Cowboys
23  Planet of the Apes
24  Star Wars: Clone Wars: Volume 1
25  Wing Commander
26  Star Trek
27  Sunshine
28  Shadow Conspiracy
29  Crocodile Dundee

Movie recomendation system

In [ ]:

movie_name = input('Enter your favourite movie name: ')
list_of_all_titles= movies['title']. tolist()
find_close_match = difflib.get_close_matches (movie_name, list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = movies[movies.title == close_match] ['index']. values [0]
similarity_score = list (enumerate(similarity[index_of_the_movie]))
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print( 'Movies suggested for you : \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies[movies.index==index][ 'title']. values[0]
  if (i<30):
    print(i,'.', title_from_index)
    i+1

Enter your favourite movie name: batman
Movies suggested for you :

1 . Batman
1 . Batman Returns
1 . Batman & Robin
1 . The Dark Knight Rises
1 . Batman Begins
1 . The Dark Knight
1 . A History of Violence
1 . Superman
1 . Bedazzled
1 . Man of Steel
1 . Suicide Squad
1 . Beetlejuice
1 . The Postman Always Rings Twice
1 . Salton Sea
1 . Jonah Hex
1 . Spider-Man 3
1 . Superman Returns
1 . Mars Attacks!
1 . Spider-Man 2
1 . Exorcist II: The Heretic
1 . Reds
1 . Superman III
1 . Superman II
1 . Something's Gotta Give
1 . Multiplicity
1 . I Dreamed of Africa
1 . Catwoman
1 . Batman Forever
1 . The One
1 . Being John Malkovich
1 . Planet of the Apes
1 . Blood and Wine
1 . Wolf
1 . Cellular
1 . The Mask
1 . 8 Mile
1 . Batman
1 . Watchmen
1 . Black November
1 . Dungeons & Dragons: Wrath of the Dragon God
1 . The Sentinel
1 . Batman v Superman: Dawn of Justice
1 . The New Guy
1 . Nine 1/2 Weeks
1 . The American President
1 . Kick-Ass 2
1 . Sliding Doors
1 . Megiddo: The Omega Code 2
1 . Green Lantern
1 . Batman: The Dark Knight Returns, Part 2
1 . Royal Kill
1 . The Bucket List
1 . Superman IV: The Quest for Peace
1 . The Departed
1 . Cheap Thrills
1 . Time Bandits
1 . Ninja Assassin
1 . The 51st State
1 . The Informers
1 . Proud
1 . How Do You Know
1 . Battlefield Earth
1 . Crash
1 . Total Recall
1 . Jekyll and Hyde ... Together Again
1 . Kick-Ass
1 . People I Know
1 . The Pledge
1 . The Last Castle
1 . As Good as It Gets
1 . Steel
1 . A Funny Thing Happened on the Way to the Forum
1 . Some Like It Hot
1 . Spotlight
1 . Logan's Run
1 . Top Gun
1 . On the Waterfront
1 . Hoffa
1 . Bless the Child
1 . Gran Torino
1 . My Stepmother is an Alien
1 . The 6th Day
1 . Never Say Never Again
1 . White Noise
1 . Creepshow
1 . Alice in Wonderland
1 . The Company
1 . Escape from Alcatraz
1 . It's a Mad, Mad, Mad, Mad World
1 . A Few Good Men
1 . About Schmidt
1 . Cypher
1 . Undercover Brother
1 . Red Tails
1 . The Whole Nine Yards
1 . The Corruptor
1 . Hang 'em High
1 . Parker
1 . The Robe
1 . Eden Lake
1 . RoboCop
1 . Creature
1 . Special
1 . Herbie Fully Loaded
1 . The Pallbearer
1 . Split Second
1 . Edward Scissorhands
1 . Sisters in Law
1 . The Grace Card
1 . Star Trek: Insurrection
1 . The Death and Life of Bobby Z
1 . Little Black Book
1 . One Flew Over the Cuckoo's Nest
1 . The Box
1 . Hardball
1 . Miss Congeniality
1 . London Has Fallen
1 . Grindhouse
1 . The Wizard of Oz
1 . Fight Club
1 . Soul Surfer
1 . Source Code
1 . Hanging Up
1 . Out of Time
1 . Star Trek: Nemesis
1 . Ghost Rider
1 . Battle for the Planet of the Apes
1 . The Abyss
1 . Devil's Due
1 . Movie 43
1 . Mi America
1 . The Karate Kid
1 . Iguana
1 . The Misfits
1 . Only God Forgives
1 . The Shining
1 . You Can't Take It With You
1 . The Forbidden Kingdom
1 . This Is Martin Bonner
1 . Fruitvale Station
1 . Star Trek: First Contact
1 . Shark Lake
1 . Assassins
1 . Star Trek: Generations
1 . Birdman
1 . City of Angels
1 . The Godfather: Part II
1 . Fantastic 4: Rise of the Silver Surfer
1 . The Killer Inside Me
1 . Anchorman: The Legend of Ron Burgundy
1 . Compliance
1 . Firefox
1 . Underworld
1 . The Beastmaster
1 . Defendor
1 . The Object of My Affection
1 . Bang
1 . Spy Kids
1 . Big Fish
1 . Kindergarten Cop
1 . The Ice Pirates
1 . Lethal Weapon 4
1 . Spellbound
1 . Star Wars: Clone Wars: Volume 1
1 . Mad Money
1 . Wrong Turn
1 . Eagle Eye
1 . Chronicle
1 . And So It Goes
1 . The Pursuit of D.B. Cooper
1 . One Hour Photo
1 . Street Fighter: The Legend of Chun-Li
1 . Arn: The Knight Templar
1 . Hollow Man
1 . The Bone Collector
1 . The Man
1 . Red State
1 . Gamer
1 . Keeping the Faith
1 . X-Men: Days of Future Past
1 . The Sorcerer's Apprentice
1 . The Hunger Games
1 . Transporter 2
1 . Firestarter
1 . The Hoax
1 . Hannah Montana: The Movie
1 . Taxman
1 . Double Impact
1 . Atlantis: The Lost Empire
1 . Boyhood
1 . Grace Unplugged
1 . Much Ado About Nothing
1 . Men in Black
1 . Back to the Future
1 . The Mexican
1 . Alvin and the Chipmunks: The Squeakquel
1 . Minions
1 . The Medallion
1 . The Wiz
1 . The Gambler
1 . The Family Stone
1 . Treasure Planet
1 . High Road
1 . Stargate: The Ark of Truth
1 . Rubber
1 . The Divide
1 . Dredd
1 . Wild Card
1 . Mean Streets
1 . Family Plot
1 . Undisputed
1 . Under the Tuscan Sun
1 . Pirates of the Caribbean: At World's End
1 . The Jackal
1 . Megamind
1 . The Net
1 . Crazy Heart
1 . Murder by Numbers
1 . The Gunman
1 . Cleopatra
1 . Precious
1 . The Godfather: Part III
1 . Zero Effect
1 . Memoirs of an Invisible Man
1 . The Game
1 . Hardflip
1 . Spy Game
1 . The Midnight Meat Train
1 . The Terminator
1 . The Station Agent
1 . Criminal Activities
1 . Darling Companion
1 . Underworld: Evolution
1 . Running with Scissors
1 . TMNT
1 . Left Behind
1 . Kill the Messenger
1 . A League of Their Own
1 . Teenage Mutant Ninja Turtles II: The Secret of the Ooze
1 . Halloween III: Season of the Witch
1 . Femme Fatale
1 . Songcatcher
1 . Cop Land
1 . The Spirit
1 . Poltergeist III
1 . Indiana Jones and the Last Crusade
1 . Kill Bill: Vol. 2
1 . Inspector Gadget
1 . Evil Dead
1 . Saint Ralph
1 . Evan Almighty
1 . Deadline - U.S.A.
1 . Frankenweenie
1 . The Haunted Mansion
1 . Rotor DR1
1 . Chasing Liberty
1 . Delivery Man
1 . Laws of Attraction
1 . The Bourne Identity
1 . Pulp Fiction
1 . Big Trouble in Little China
1 . Our Kind of Traitor
1 . 28 Days
1 . Goosebumps
1 . About Time
1 . Lions for Lambs
1 . Dark Shadows
1 . Back to the Future Part III
1 . Extreme Movie
1 . Moon
1 . Year One
1 . Frances Ha
1 . This Is England
1 . Boogie Nights
1 . Children of Men
1 . Checkmate
1 . Death Becomes Her
1 . Alex Cross
1 . The Vatican Tapes
1 . Bronson
1 . Along Came a Spider
1 . Saw IV
1 . Chill Factor
1 . Dick Tracy
1 . Austin Powers: The Spy Who Shagged Me
1 . Albert Nobbs
1 . I Am Number Four
1 . Charlie's Angels: Full Throttle
1 . Men in Black 3
1 . Con Air
1 . Supercapitalist
1 . The Scorpion King
1 . The Adventurer: The Curse of the Midas Box
1 . Below Zero
1 . The Postman
1 . Dragonslayer
1 . The Last Samurai
1 . Halloween: The Curse of Michael Myers
1 . Eraserhead
1 . Spawn
1 . Thinner
1 . The Chronicles of Riddick
1 . Corpse Bride
1 . Romeo Must Die
1 . Cape Fear
1 . Hot Pursuit
1 . Mission: Impossible II
1 . The DUFF
1 . What's Eating Gilbert Grape
1 . The Protector
1 . Pale Rider
1 . Open Range
1 . The Cabin in the Woods
1 . Enemy of the State
1 . Road to Perdition
1 . The Innkeepers
1 . Sweet November
1 . FearDotCom
1 . Class of 1984
1 . Mercury Rising
1 . Mississippi Mermaid
1 . GoodFellas
1 . Million Dollar Arm
1 . Capote
1 . Charlie and the Chocolate Factory
1 . Pirates of the Caribbean: The Curse of the Black Pearl
1 . The Curious Case of Benjamin Button
1 . Don Juan DeMarco
1 . The Omega Code
1 . Saving Silverman
1 . Down Terrace
1 . Alleluia! The Devil's Carnival
1 . Connie and Carla
1 . Brown Sugar
1 . Blood Ties
1 . Dr. No
1 . The Heat
1 . Tango & Cash
1 . The Legend of the Lone Ranger
1 . A Perfect Getaway
1 . King Kong
1 . The Land Before Time
1 . Takers
1 . Stuart Little
1 . Marvin's Room
1 . The Last House on the Left
1 . Identity Thief
1 . Fantasia
1 . Harry Potter and the Order of the Phoenix
1 . Ed Wood
1 . The Waterboy
1 . A Most Violent Year
1 . Four Rooms
1 . Dressed to Kill
1 . Notting Hill
1 . The Lion King
1 . School of Rock
1 . The Yards
1 . Boys Don't Cry
1 . Monte Carlo
1 . The Crow
1 . The Land Girls
1 . The Green Mile
1 . The Brass Teapot
1 . Run Lola Run
1 . From Hell
1 . Mortal Kombat: Annihilation
1 . Rescue Dawn
1 . The Cat in the Hat
1 . Conquest of the Planet of the Apes
1 . The Man from Snowy River
1 . Chloe
1 . The Life Aquatic with Steve Zissou
1 . Bully
1 . Monster-in-Law
1 . Jackie Brown
1 . Get Rich or Die Tryin'
1 . You've Got Mail
1 . Dumb and Dumber
1 . Clockstoppers
1 . Premium Rush
1 . Small Time Crooks
1 . Sleeper
1 . Hud
1 . You, Me and Dupree
1 . Def-Con 4
1 . What Dreams May Come
1 . Highlander: The Final Dimension
1 . Dark Blue
1 . Casa De Mi Padre
1 . She's the One
1 . Dragonball Evolution
1 . The Hundred-Foot Journey
1 . The Man with the Golden Gun
1 . Lucky Number Slevin
1 . Breakdown
1 . Aloha
1 . Observe and Report
1 . The Stepford Wives
1 . First Blood
1 . Funny Games
1 . Clean
1 . Kate & Leopold
1 . Black Swan
1 . Underworld: Rise of the Lycans
1 . The Dead Zone
1 . Stand by Me
1 . Excessive Force
1 . The Prisoner of Zenda
1 . Caravans
1 . The Good Dinosaur
1 . Angel Eyes
1 . Pirates of the Caribbean: Dead Man's Chest
1 . Pitch Black
1 . Day of the Dead
1 . Stan Helsing
1 . Sucker Punch
1 . An Inconvenient Truth
1 . See Spot Run
1 . Where the Wild Things Are
1 . Wild Things
1 . The Missing Person
1 . Analyze This
1 . A Dangerous Method
1 . Ride Along 2
1 . National Treasure
1 . Star Trek IV: The Voyage Home
1 . X-Men: First Class
1 . The Princess and the Frog
1 . Code 46
1 . Flightplan
1 . Midnight in Paris
1 . Men in Black II
1 . The Cotton Club
1 . Spaceballs
1 . Glengarry Glen Ross
1 . Teen Wolf Too
1 . Aliens vs Predator: Requiem
1 . The Switch
1 . Half Past Dead
1 . All the Boys Love Mandy Lane
1 . My Fellow Americans
1 . Because I Said So
1 . The Mortal Instruments: City of Bones
1 . Mumford
1 . J. Edgar
1 . Do the Right Thing
1 . Small Soldiers
1 . End of Watch
1 . The Ghost Writer
1 . TRON: Legacy
1 . Harry Brown
1 . How Stella Got Her Groove Back
1 . Music and Lyrics
1 . One True Thing
1 . Without a Paddle
1 . Fear and Loathing in Las Vegas
1 . 16 Blocks
1 . Ri¢hie Ri¢h
1 . The Back-Up Plan
1 . Hitman
1 . I Love You, Don't Touch Me!
1 . The Other Guys
1 . Of Gods and Men
1 . Underworld: Awakening
1 . Forbidden Kingdom
1 . Urban Legend
1 . Scary Movie 4
1 . Secret in Their Eyes
1 . Nebraska
1 . Police Academy
1 . Wall Street: Money Never Sleeps
1 . Michael Clayton
1 . The Last Song
1 . When the Game Stands Tall
1 . The Spanish Prisoner
1 . Lady in White
1 . Tootsie
1 . Your Sister's Sister
1 . The Soloist
1 . Juno
1 . Ride with the Devil
1 . The R.M.
1 . Fatal Attraction
1 . Happily N'Ever After
1 . 13 Going on 30
1 . BloodRayne
1 . The Guard
1 . Annie Hall
1 . Quinceañera
1 . City of God
1 . Soul Plane
1 . Mirrormask
1 . Cliffhanger
1 . Behind Enemy Lines
1 . Lifeforce
1 . Sex and the City 2
1 . Highlander: Endgame
1 . The Ballad of Jack and Rose
1 . Animals
1 . The Statement
1 . The Road to El Dorado
1 . Bubba Ho-tep
1 . That Thing You Do!
1 . Disturbia
1 . Colombiana
1 . History of the World: Part I
1 . West Side Story
1 . Savva. Heart of the Warrior
1 . The Emperor's Club
1 . Flashdance
1 . The Devil's Double
1 . I, Frankenstein
1 . The Adventures of Huck Finn
1 . Seventh Son
1 . Tin Can Man
1 . Witness
1 . Man of the House
1 . Centurion
1 . A Fistful of Dollars
1 . Like Crazy
1 . Masked and Anonymous
1 . The Ladykillers
1 . Inkheart
1 . Swept Away
1 . Bound
1 . Jumper
1 . Waiting for Guffman
1 . The English Patient
1 . Blood Done Sign My Name
1 . The First Wives Club
1 . Changing Lanes
1 . Astro Boy
1 . Caddyshack
1 . A Night at the Roxbury
1 . Safe
1 . Good Night, and Good Luck.
1 . City By The Sea
1 . The Lovely Bones
1 . Autumn in New York
1 . The Life of David Gale
1 . My Life in Ruins
1 . The Prestige
1 . Inside Deep Throat
1 . Spider-Man
1 . Mission: Impossible III
1 . Tuck Everlasting
1 . Decoys
1 . Rampage
1 . 3 Strikes
1 . Surrogates
1 . Sympathy for Lady Vengeance
1 . In Good Company
1 . The Rock
1 . Admission
1 . Kingdom of Heaven
1 . Captain Corelli's Mandolin
1 . Toy Story 2
1 . The Beyond
1 . Hit & Run
1 . Six-String Samurai
1 . The Lion of Judah
1 . Arthur Christmas
1 . Kangaroo Jack
1 . School for Scoundrels
1 . Paul
1 . Banshee Chapter
1 . The Brothers McMullen
1 . Evil Dead II
1 . Tucker and Dale vs Evil
1 . Barbershop 2:  Back in Business
1 . Before Sunset
1 . The Ten
1 . A Bridge Too Far
1 . Barnyard
1 . Inglourious Basterds
1 . Spy Hard
1 . The Andromeda Strain
1 . Teenage Mutant Ninja Turtles III
1 . The Naked Gun 2½: The Smell of Fear
1 . Aliens in the Attic
1 . The Twilight Saga: Eclipse
1 . Midnight in the Garden of Good and Evil
1 . Legend of a Rabbit
1 . Paddington
1 . Training Day
1 . Conan the Destroyer
1 . Super Size Me
1 . The Virgin Suicides
1 . Mortal Kombat
1 . Silent Hill
1 . The Art of War
1 . Capitalism: A Love Story
1 . Snowpiercer
1 . Take Shelter
1 . I Am Legend
1 . Scrooged
1 . Big Eyes
1 . Waking Ned
1 . Child's Play 2
1 . Master and Commander: The Far Side of the World
1 . Sausage Party
1 . Big Trouble
1 . Horrible Bosses
1 . Sin City
1 . The Muppet Christmas Carol
1 . In Dreams
1 . Kung Fu Panda 3
1 . The Lord of the Rings: The Return of the King
1 . Trucker
1 . Last I Heard
1 . The Big Wedding
1 . Harry Potter and the Half-Blood Prince
1 . Black Book
1 . Lone Wolf McQuade
1 . The Black Stallion
1 . The Longest Yard
1 . Tremors
1 . R.I.P.D.
1 . Eight Below
1 . Love the Coopers
1 . Y Tu Mamá También
1 . Food, Inc.
1 . Shooter
1 . The Prophecy
1 . 8MM
1 . L.A. Confidential
1 . Hesher
1 . The Infiltrator
1 . Topaz
1 . Random Hearts
1 . Phenomenon
1 . I Want Your Money
1 . Swimfan
1 . The League of Extraordinary Gentlemen
1 . Last Action Hero
1 . The Weather Man
1 . Black Rain
1 . Pocketful of Miracles
1 . The Replacement Killers
1 . Gun Shy
1 . The Flintstones
1 . 2046
1 . Reign of Fire
1 . The Kid
1 . Donnie Brasco
1 . Harold & Kumar Escape from Guantanamo Bay
1 . Cop Out
1 . My Best Friend's Wedding
1 . The Incredibles
1 . High Heels and Low Lifes
1 . Riding in Cars with Boys
1 . The Ghost and the Darkness
1 . Sphere
1 . JFK
1 . Brokedown Palace
1 . Town & Country
1 . Think Like a Man
1 . Don't Be Afraid of the Dark
1 . Reservoir Dogs
1 . Stay Alive
1 . Cars 2
1 . Holy Motors
1 . Dark Water
1 . Nim's Island
1 . Revolutionary Road
1 . Crocodile Dundee
1 . UHF
1 . A Streetcar Named Desire
1 . Nine Dead
1 . The Book of Mormon Movie, Volume 1: The Journey
1 . Patriot Games
1 . Braveheart
1 . The Equalizer
1 . The Omen
1 . Mr. & Mrs. Smith
1 . Point Blank
1 . Domino
1 . Patton
1 . The Polar Express
1 . Disclosure
1 . Shark Tale
1 . Antarctica: A Year on Ice
1 . Fever Pitch
1 . The Hobbit: An Unexpected Journey
1 . Open Water
1 . Dinosaur
1 . The Nutcracker
1 . Night at the Museum: Battle of the Smithsonian
1 . 21 Grams
1 . True Romance
1 . Porky's
1 . Thunderball
1 . Racing Stripes
1 . S.W.A.T.
1 . Stuck on You
1 . Safe Men
1 . Munich
1 . Little Boy
1 . Stranded
1 . The Singles Ward
1 . 17 Again
1 . On Deadly Ground
1 . Snitch
1 . American Ninja 2: The Confrontation
1 . Being Julia
1 . Z Storm
1 . Nanny McPhee and the Big Bang
1 . Nothing to Lose
1 . Beneath the Planet of the Apes
1 . Monsoon Wedding
1 . Flash Gordon
1 . The Art of Getting By
1 . The Hotel New Hampshire
1 . American Heist
1 . Wall Street
1 . Daybreakers
1 . Josie and the Pussycats
1 . Warriors of Virtue
1 . Sea of Love
1 . Think Like a Man Too
1 . Willy Wonka & the Chocolate Factory
1 . Tusk
1 . Madison
1 . Mrs. Winterbourne
1 . Police Academy: Mission to Moscow
1 . X-Men: Apocalypse
1 . Carriers
1 . Inception
1 . The Princess Bride
1 . Captive
1 . The Kentucky Fried Movie
1 . Fish Tank
1 . Cold Mountain
1 . Rapa Nui
1 . Escape from the Planet of the Apes
1 . Mutant World
1 . Lone Star
1 . Kung Fu Panda 2
1 . Forrest Gump
1 . Lincoln
1 . The Image Revolution
1 . The Big Bounce
1 . The Hurt Locker
1 . The Helix... Loaded
1 . The Blair Witch Project
1 . To Write Love on Her Arms
1 . Bending Steel
1 . Flash of Genius
1 . Turbulence
1 . Mystic Pizza
1 . The Phantom
1 . Hannibal Rising
1 . Princess Mononoke
1 . A Mighty Wind
1 . Midnight Cabaret
1 . Sky High
1 . Employee of the Month
1 . Kill List
1 . Darling Lili
1 . Me and Orson Welles
1 . Hope Floats
1 . Eragon
1 . The Mummy Returns
1 . He's Just Not That Into You
1 . American Outlaws
1 . Valley of the Heart's Delight
1 . The Conversation
1 . Leaving Las Vegas
1 . Ice Princess
1 . Twilight
1 . Night at the Museum
1 . Little Women
1 . Peggy Sue Got Married
1 . After.Life
1 . The Tourist
1 . The Invention of Lying
1 . The Square
1 . Torn Curtain
1 . Stolen Summer
1 . Harry Potter and the Chamber of Secrets
1 . Harry Potter and the Goblet of Fire
1 . Dear Wendy
1 . The Hobbit: The Battle of the Five Armies
1 . The Basket
1 . Lucky Numbers
1 . I Got the Hook Up
1 . Tropic Thunder
1 . Ishtar
1 . Talladega Nights: The Ballad of Ricky Bobby
1 . How the Grinch Stole Christmas
1 . Southland Tales
1 . Bamboozled
1 . Drop Dead Gorgeous
1 . The Score
1 . Redbelt
1 . Orgazmo
1 . Finding Forrester
1 . The Shallows
1 . Ultramarines: A Warhammer 40,000 Movie
1 . Friday After Next
1 . Dick
1 . The 40 Year Old Virgin
1 . Inside Man
1 . My Boss's Daughter
1 . The Iceman
1 . Noah
1 . Robot & Frank
1 . That Awkward Moment
1 . Along the Roadside
1 . Muppets from Space
1 . Waterloo
1 . The Adventures of Elmo in Grouchland
1 . The Bourne Supremacy
1 . Hancock
1 . This Is It
1 . Paris, je t'aime
1 . K-PAX
1 . DOA: Dead or Alive
1 . My Girl
1 . Harry Potter and the Philosopher's Stone
1 . The Sitter
1 . Resident Evil: Afterlife
1 . The Fisher King
1 . Falcon Rising
1 . A Thin Line Between Love and Hate
1 . The Apartment
1 . Iron Man 2
1 . Killing Them Softly
1 . The Wolfman
1 . 10th & Wolf
1 . Winter Passing
1 . Licence to Kill
1 . Without Limits
1 . For Your Consideration
1 . Freaky Deaky
1 . To Save A Life
1 . Ocean's Eleven
1 . Jindabyne
1 . The Cooler
1 . The Adventures of Rocky & Bullwinkle
1 . Pride and Glory
1 . Fantastic Four
1 . Outbreak
1 . Atlas Shrugged Part II
1 . Quo Vadis
1 . 8 Days
1 . Man on a Ledge
1 . Terminator 2: Judgment Day
1 . Predator 2
1 . Woo
1 . Frost/Nixon
1 . March or Die
1 . Made of Honor
1 . Raiders of the Lost Ark
1 . Be Kind Rewind
1 . Austin Powers in Goldmember
1 . Love in the Time of Monsters
1 . All Good Things
1 . A Dog Of Flanders
1 . Dr. Dolittle 2
1 . Swing Vote
1 . Rudderless
1 . The BFG
1 . Emma
1 . Nowhere to Run
1 . Aliens
1 . Species
1 . Bowling for Columbine
1 . Return of the Jedi
1 . Disturbing Behavior
1 . The Counselor
1 . Star Trek II: The Wrath of Khan
1 . Jimmy and Judy
1 . Take Me Home Tonight
1 . Groundhog Day
1 . Perfume: The Story of a Murderer
1 . Renaissance
1 . Come Early Morning
1 . And Then Came Love
1 . Righteous Kill
1 . Running Scared
1 . Damnation Alley
1 . Crazy/Beautiful
1 . Miss Potter
1 . What Planet Are You From?
1 . The Rookie
1 . Unfinished Business
1 . Alien: Resurrection
1 . The Astronaut's Wife
1 . Legal Eagles
1 . Sugar Town
1 . Saw
1 . Chain of Command
1 . River's Edge
1 . 12 Years a Slave
1 . Cat on a Hot Tin Roof
1 . Getaway
1 . Lara Croft Tomb Raider: The Cradle of Life
1 . Maleficent
1 . Scott Pilgrim vs. the World
1 . Under Siege 2: Dark Territory
1 . Interstellar
1 . Cloverfield
1 . The Hunt for Red October
1 . Space Jam
1 . The Family Man
1 . O Brother, Where Art Thou?
1 . Born Of War
1 . The Girl with the Dragon Tattoo
1 . Bad Boys II
1 . Book of Shadows: Blair Witch 2
1 . Jade
1 . The Ant Bully
1 . A Nightmare on Elm Street Part 2: Freddy's Revenge
1 . The Hunger Games: Catching Fire
1 . Trash
1 . Sexy Beast
1 . Alien Zone
1 . High Crimes
1 . The World Is Not Enough
1 . Maid in Manhattan
1 . Dead Like Me: Life After Death
1 . Haywire
1 . Step Up
1 . Shallow Hal
1 . Wristcutters: A Love Story
1 . G-Force
1 . Once
1 . House of Sand and Fog
1 . Navy Seals vs. Zombies
1 . City Hall
1 . They
1 . A Passage to India
1 . Agora
1 . Prometheus
1 . World Trade Center
1 . The Charge of the Light Brigade
1 . Gangs of New York
1 . Gangster's Paradise: Jerusalema
1 . End of the Spear
1 . Thr3e
1 . Code Name: The Cleaner
1 . Body Double
1 . Driven
1 . Redemption Road
1 . Blue Streak
1 . Secondhand Lions
1 . Earth to Echo
1 . Sugar Hill
1 . Austin Powers: International Man of Mystery
1 . Eye of the Beholder
1 . Straightheads
1 . Hairspray
1 . Diary of the Dead
1 . Woman Thou Art Loosed
1 . Piranha 3D
1 . The Sound of Music
1 . Cruel Intentions
1 . Casablanca
1 . The Newton Boys
1 . Who's Your Caddy?
1 . Young Guns
1 . Muppets Most Wanted
1 . The Opposite Sex
1 . Bottle Rocket
1 . Truth or Dare
1 . Dragon Blade
1 . Treachery
1 . End of Days
1 . Man on Wire
1 . Wreck-It Ralph
1 . Beyond the Black Rainbow
1 . Frenzy
1 . Failure to Launch
1 . The Book of Eli
1 . Practical Magic